// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf3r2dDKzzW5fwl9kPLP8I6WXF5Np_IkI',
    appId: '1:684237390844:android:75be86a16c9f4ce6eb2879',
    messagingSenderId: '684237390844',
    projectId: 'rain-8fb4b',
    storageBucket: 'rain-8fb4b.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDec4SCe3BwC8VqzjQelE9sPKEzSUDiZ_4',
    appId: '1:684237390844:ios:121b7f9bd22e86fbeb2879',
    messagingSenderId: '684237390844',
    projectId: 'rain-8fb4b',
    storageBucket: 'rain-8fb4b.firebasestorage.app',
    iosBundleId: 'com.rainapp.rain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMYzi44ZEn4CK6zc2CvZTxK_zlY1HgEOk',
    appId: '1:684237390844:web:61bacca9b5122288eb2879',
    messagingSenderId: '684237390844',
    projectId: 'rain-8fb4b',
    authDomain: 'rain-8fb4b.firebaseapp.com',
    storageBucket: 'rain-8fb4b.firebasestorage.app',
    measurementId: 'G-YG21DP3T0L',
  );
}
