// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `accept_peer_in_state`, `connect_peer_in_state`, `connection_from_state`, `diagnostics_event`, `disconnect_peer_in_state`, `emit_event`, `endpoint_from_state`, `read_loop`, `register_connection`, `runtime_state`, `send_frame_in_state`, `start_endpoint_in_state`, `stop_endpoint_in_state`, `validate_remote`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `IrohEvent`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<IrohEndpointInfo> irohStartEndpoint({
  required String username,
  required String alpn,
}) => RustLib.instance.api.crateApiIrohTransportIrohStartEndpoint(
  username: username,
  alpn: alpn,
);

Future<void> irohStopEndpoint() =>
    RustLib.instance.api.crateApiIrohTransportIrohStopEndpoint();

Future<void> irohConnectPeer({
  required String peerId,
  required String endpointAddr,
  required String expectedNodeId,
  required String alpn,
  required String connectAttemptId,
  required String sessionSecret,
}) => RustLib.instance.api.crateApiIrohTransportIrohConnectPeer(
  peerId: peerId,
  endpointAddr: endpointAddr,
  expectedNodeId: expectedNodeId,
  alpn: alpn,
  connectAttemptId: connectAttemptId,
  sessionSecret: sessionSecret,
);

Future<void> irohAcceptPeer({
  required String peerId,
  required String expectedNodeId,
  required String alpn,
  required String connectAttemptId,
  required String sessionSecret,
}) => RustLib.instance.api.crateApiIrohTransportIrohAcceptPeer(
  peerId: peerId,
  expectedNodeId: expectedNodeId,
  alpn: alpn,
  connectAttemptId: connectAttemptId,
  sessionSecret: sessionSecret,
);

Future<void> irohDisconnectPeer({required String peerId}) => RustLib
    .instance
    .api
    .crateApiIrohTransportIrohDisconnectPeer(peerId: peerId);

Future<void> irohSend({
  required String peerId,
  required String channel,
  required List<int> payload,
}) => RustLib.instance.api.crateApiIrohTransportIrohSend(
  peerId: peerId,
  channel: channel,
  payload: payload,
);

Future<BigInt> irohBufferedAmount({
  required String peerId,
  required String channel,
}) => RustLib.instance.api.crateApiIrohTransportIrohBufferedAmount(
  peerId: peerId,
  channel: channel,
);

Stream<String> irohEventStream() =>
    RustLib.instance.api.crateApiIrohTransportIrohEventStream();

class IrohEndpointInfo {
  final String nodeId;
  final String endpointAddr;

  const IrohEndpointInfo({required this.nodeId, required this.endpointAddr});

  @override
  int get hashCode => nodeId.hashCode ^ endpointAddr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IrohEndpointInfo &&
          runtimeType == other.runtimeType &&
          nodeId == other.nodeId &&
          endpointAddr == other.endpointAddr;
}
